apiVersion: v1
kind: Pod
metadata:
  name: spark-driver
spec:
  containers:
  - name: spark-driver-container
    image: ilyassifez/spark:testy
    imagePullPolicy: Always
  nodeSelector:
    spark: yes
