version: "3.8"
services:
#Spark job initiator
  spark:
    image: ilyassifez/bdataprojectpython:sparky
    container_name: spark
    command: ["python3.8","main.py"]
    environment:
      ACCESS_KEY: $ACCESS_KEY
      SECRET_KEY: $SECRET_KEY
      REGION: $REGION
